In [1]:
import numpy as np
matriz = np.array([ [1, 2, 3], [4, 5, 6] ])
print('Original:', matriz.shape)
print(matriz)
print('\nTranspuesta:', matriz.T.shape)
print(matriz.T)

Original: (2, 3)
[[1 2 3]
 [4 5 6]]

Transpuesta: (3, 2)
[[1 4]
 [2 5]
 [3 6]]


In [3]:
arr = np.array([[1, 2], [3, 4]])

a = arr.flat
print(a)

for elemento in arr.flat:
    print(elemento, end=' ')

1 2 3 4 

In [6]:
arr1d = np.arange(12)
print(f'Original: {arr1d}')
arr2d = arr1d.reshape(3, 4)
print('\nReshape a 3x4:')
print(arr2d)

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshape a 3x4:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [12]:
arr_auto = arr1d.reshape(3, -1) # Infiere 4 columnas
print(arr_auto.shape) # (3, 4)

print(arr_auto)

# arr_auto[0][0] = 99
print(arr1d)

(3, 4)
[[99  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[99  1  2  3  4  5  6  7  8  9 10 11]


In [14]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])
plano = matriz.flatten()
print(plano) # [1 2 3 4 5 6]
print("-" * 20)
# Es una copia independiente
plano[0] = 999
print(plano)
print("-" * 20)
print(matriz[0, 0]) # 1 (no cambió)

[1 2 3 4 5 6]
--------------------
[999   2   3   4   5   6]
--------------------
1


In [16]:
import numpy as np
matriz = np.array([[1, 2],
                   [3, 4]])
plano = matriz.ravel()
print(plano) # [1 2 3 4]
# Es una vista, modificar afecta al original
plano[0] = 999
print(matriz) # [[999 2] [ 3 4]]

[1 2 3 4]
[[999   2]
 [  3   4]]


In [18]:
import numpy as np
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
# Orden 'C' (por filas) - predeterminado
# ravel_c = matriz.ravel(order='C')  # Metodo
ravel_c = np.ravel(matriz, order='C') # Funcion de NumPy
print(ravel_c)
# [1 2 3 4 5 6 7 8 9]
# Lee: fila1 completa, luego fila2, luego fila3

# Orden 'F' (por columnas)
ravel_f = matriz.ravel(order='F')
print(ravel_f)
# [1 4 7 2 5 8 3 6 9]

[1 2 3 4 5 6 7 8 9]
[1 4 7 2 5 8 3 6 9]


In [19]:
import numpy as np
# Matriz 2x3
matriz = np.array([[1, 2, 3],
[4, 5, 6]])
print("Matriz original:")
print(matriz)
print(f"Shape: {matriz.shape}")
# Transponer
transpuesta = matriz.transpose()
# o simplemente: matriz.T
print("\nMatriz transpuesta:")
print(transpuesta)
print(f"Shape: {transpuesta.shape}")

Matriz original:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

Matriz transpuesta:
[[1 4]
 [2 5]
 [3 6]]
Shape: (3, 2)


In [20]:
import numpy as np
a = np.array([[1, 2, 3],
[4, 5, 6]])
# Forma 1: Método transpose()
t1 = a.transpose()
# Forma 2: Atributo .T (más común y conciso)
t2 = a.T
# Forma 3: Función np.transpose()
t3 = np.transpose(a)
# Todas son equivalentes
print(np.array_equal(t1, t2)) # True
print(np.array_equal(t1, t3)) # True

True
True


In [21]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(f'Suma total: {arr.sum()}') # 21
print(f'Por columnas: {arr.sum(axis=0)}') # [5 7 9]
print(f'Por filas: {arr.sum(axis=1)}') # [ 6 15]

Suma total: 21
Por columnas: [5 7 9]
Por filas: [ 6 15]


In [22]:
datos = np.array([10, 20, 20, 30, 40, 50, 1000])
print(f'Media: {np.mean(datos):.2f}') # 30.0
print(f'Mediana: {np.median(datos):.2f}') # 30.0
print(f'Desv. estándar: {datos.std():.2f}')
print(f'Varianza: {datos.var():.2f}')

Media: 167.14
Mediana: 30.00
Desv. estándar: 340.24
Varianza: 115763.27


In [23]:
arr = np.array([[5, 2, 8],
                [1, 9, 3]])
print(f'Mínimo: {arr.min()}') # 1
print(f'Máximo: {arr.max()}') # 9
print(f'Índice del mín: {arr.argmin()}') # 3
print(f'Índice del máx: {arr.argmax()}') # 4

Mínimo: 1
Máximo: 9
Índice del mín: 3
Índice del máx: 4


In [24]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.cumsum()) # [ 1 3 6 10 15]
print(arr.cumprod()) # [ 1 2 6 24 120]

[ 1  3  6 10 15]
[  1   2   6  24 120]


In [26]:
arr = np.array([3, 1, 4, 5, 1])
arr.sort()
print(arr) # [1 1 3 4 5]

[1 1 3 4 5]


In [27]:
arr = np.array([30, 10, 20, 50, 40])
indices = arr.argsort()
print(f'Índices: {indices}') # [1 2 0 4 3]
print(f'Ordenado: {arr[indices]}') # [10 20 30 40 50]
print(f"Origina: {arr}")

Índices: [1 2 0 4 3]
Ordenado: [10 20 30 40 50]
Origina: [30 10 20 50 40]
