In [1]:
def sumar(num_1, num_2):
  suma = num_1 + num_2
  return suma

print(sumar(5, 8))
print(sumar(78, -30))

13
48


In [3]:
print(sumar(45,23))

68


In [4]:
def promedio(pp, ep, ef):
  pass

pr = promedio(15, 12, 18)
print(pr)

None


In [6]:
def saludar(nombre):
  print("Hola", nombre)

saludar("Gustavo Coronel")

Hola Gustavo Coronel


In [8]:
def media(num_1, num_2, num_3):
  suma = num_1 + num_2 + num_3
  prom = suma / 3
  return prom

promedio = media(17, 19, 15);
print("Promedio:", promedio)

Promedio: 17.0


In [9]:
def media(num_1, num_2, num_3):
  return (num_1 + num_2 + num_3) / 3

promedio = media(17, 19, 15);
print("Promedio:", promedio)

Promedio: 17.0


In [11]:
def media(num_1, num_2, num_3):
  return (num_1 + num_2 + num_3) / 3

print(media(15, 17, 19)) # num_1 = 15, num_2 = 17, num_3 = 19
print(media(num_3=15, num_1=17, num_2=19)) # num_1 = 17, num_19 = 17, num_3 = 15

17.0
17.0


In [12]:
def media(num_1=10, num_2=8, num_3=6):
  return (num_1 + num_2 + num_3) / 3

print(media())

8.0


In [15]:
suma = 1000

def media(num_1, num_2, num_3):
  suma = num_1 + num_2 + num_3
  prom = suma / 3
  return prom

promedio = media(17, 19, 15);
print("Suma:", suma) # 1000 o 51
print("Promedio:", promedio)

Suma: 1000
Promedio: 17.0


In [16]:
suma = 1000

def media(num_1, num_2, num_3):
  global suma
  suma = num_1 + num_2 + num_3
  prom = suma / 3
  return prom

promedio = media(17, 19, 15);
print("Suma:", suma) # 1000 o 51
print("Promedio:", promedio)

Suma: 51
Promedio: 17.0


In [17]:
def sumar( lista ):
  suma = 0; # Acumulador
  for num in lista:
    suma += num
  return suma

print(sumar([34,12,56,89,23]))

214


In [18]:
def sumar( lista ):
  return sum(lista)

print(sumar([34,12,56,89,23]))

214


In [20]:
# verificar_numpy.py
import sys
def verificar_numpy_instalado():
   try:
      import numpy as np
      print(f"✓ NumPy YA está instalado")
      print(f" Versión: {np.__version__}")
      print(f" Ubicación: {np.__file__}")
      return True
   except ImportError:
      print("✗ NumPy NO está instalado")
      print(" Proceda con la instalación")
      return False

if __name__ == "__main__":
   verificar_numpy_instalado()

✓ NumPy YA está instalado
 Versión: 2.0.2
 Ubicación: /usr/local/lib/python3.12/dist-packages/numpy/__init__.py


In [21]:
import sys
import numpy as np
print("=" * 60)
print("VERIFICACIÓN DEL ENTORNO DE TRABAJO")
print("=" * 60)
print(f"\nPython: {sys.version}")
print(f"Ubicación: {sys.executable}")
print(f"\nNumPy: {np.__version__}")
print(f"Ubicación: {np.__file__}")

VERIFICACIÓN DEL ENTORNO DE TRABAJO

Python: 3.12.12 (main, Oct 10 2025, 08:52:57) [GCC 11.4.0]
Ubicación: /usr/bin/python3

NumPy: 2.0.2
Ubicación: /usr/local/lib/python3.12/dist-packages/numpy/__init__.py


In [23]:
# Crear un arreglo simple
arr = np.array([1, 2, 3, 4, 5])
print("\nARREGLO CREADO:")
print(f"Contenido: {arr}")
print(f"Tipo: {type(arr)}")
print(f"Forma: {arr.shape}")
print(f"Tipo de datos: {arr.dtype}")
print("\nOPERACIONES BÁSICAS:")
print(f"Suma: {np.sum(arr)}")
print(f"Media: {np.mean(arr)}")
print(f"Desviación estándar: {np.std(arr)}")
print(f"Mínimo: {np.min(arr)}")
print(f"Máximo: {np.max(arr)}")


ARREGLO CREADO:
Contenido: [1 2 3 4 5]
Tipo: <class 'numpy.ndarray'>
Forma: (5,)
Tipo de datos: int64

OPERACIONES BÁSICAS:
Suma: 15
Media: 3.0
Desviación estándar: 1.4142135623730951
Mínimo: 1
Máximo: 5


In [24]:
import numpy as np
# Crear un escalar
escalar = np.array(42)
print(escalar)
print(f"Dimensiones: {escalar.ndim}")
print(f"Forma: {escalar.shape}")

42
Dimensiones: 0
Forma: ()


In [26]:
# Desde una lista
arr1d = np.array([1, 2, 3, 4, 5])
print(arr1d)
print(f"Tipo: {type(arr1d)}")
print(f"Dimensiones: {arr1d.ndim}")
print(f"Forma: {arr1d.shape}")
print(f"Tamaño: {arr1d.size}")

[1 2 3 4 5]
Tipo: <class 'numpy.ndarray'>
Dimensiones: 1
Forma: (5,)
Tamaño: 5


In [27]:
# NumPy acepta tanto listas como tuplas
arr_tupla = np.array((10, 20, 30, 40))
print(arr_tupla)

[10 20 30 40]


In [30]:
# Crear una matriz 3x3
arr2d = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9],
[6,2,9]])
print(arr2d)
print(f"Dimensiones: {arr2d.ndim}")
print(f"Forma: {arr2d.shape}")
print(f"Tamaño total: {arr2d.size}")

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [6 2 9]]
Dimensiones: 2
Forma: (4, 3)
Tamaño total: 12


In [32]:
# Arreglo 3-D (2x2x2)
arr3d = np.array(
    [[[1, 2], [3, 4]],
    [[5, 6], [7, 8]],
     [[5,9],[2,7]]])
print(arr3d)
print(f"Dimensiones: {arr3d.ndim}")
print(f"Forma: {arr3d.shape}")

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]

 [[5 9]
  [2 7]]]
Dimensiones: 3
Forma: (3, 2, 2)


In [33]:
# NumPy infiere int64
arr_int = np.array([1, 2, 3])
print(f"Tipo inferido: {arr_int.dtype}")

Tipo inferido: int64


In [34]:
# NumPy infiere float64
arr_float = np.array([1.0, 2.0, 3.0])
print(f"Tipo inferido: {arr_float.dtype}")

Tipo inferido: float64


In [35]:
# Especificar dtype explícitamente
arr_especifico = np.array([1, 2, 3], dtype=np)
print(f"Tipo especificado: {arr_especifico.dtype}")

Tipo especificado: float32


In [37]:
# Especificar dtype explícitamente
arr_especifico = np.array([1, 2, 3], dtype=np.float32)
print(f"Tipo especificado: {arr_especifico.dtype}")

Tipo especificado: float32


In [38]:
# Arreglo 1-D de 5 ceros
zeros_1d = np.zeros(5)
print(zeros_1d)

[0. 0. 0. 0. 0.]


In [39]:
# Matriz 2x3 de unos
ones_2d = np.ones((2, 3))
print(ones_2d)

[[1. 1. 1.]
 [1. 1. 1.]]


In [40]:
# Matriz 2x2 llena de 7
full_arr = np.full((2, 2), 7)
print(full_arr)


[[7 7]
 [7 7]]


In [42]:
# Arreglo vacío de 3 elementos
empty_arr = np.empty(3)
print(empty_arr) # Valores aleatorios

[1.3812434e-315 0.0000000e+000 1.5810101e-322]


In [43]:
# Matriz identidad 3x3
identidad = np.eye(3)
print(identidad)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [44]:
# Del 0 al 9
arange1 = np.arange(10)
print(arange1)

[0 1 2 3 4 5 6 7 8 9]


In [45]:
# Del 2 al 9
arange2 = np.arange(2, 10)
print(arange2)

[2 3 4 5 6 7 8 9]


In [46]:
# Del 0 al 20 de 2 en 2
arange3 = np.arange(0, 21, 2)
print(arange3)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [47]:
# 5 valores entre 0 y 10 (incluye ambos extremos)
linspace_arr = np.linspace(0, 10, num=5)
print(linspace_arr)

[ 0.   2.5  5.   7.5 10. ]


In [48]:
arr_1d = np.array([1, 2, 3])
arr_2d = np.array([[1, 2], [3, 4]])
arr_3d = np.array([[[1, 2]], [[3, 4]]])
print(f"1-D: {arr_1d.ndim} dimensiones")
print(f"2-D: {arr_2d.ndim} dimensiones")
print(f"3-D: {arr_3d.ndim} dimensiones")

1-D: 1 dimensiones
2-D: 2 dimensiones
3-D: 3 dimensiones


In [49]:
arr_int = np.array([1, 2, 3])
arr_float = np.array([1.5, 2.5, 3.5])
print(f"Tipo de arr_int: {arr_int.dtype}")
print(f"Tipo de arr_float: {arr_float.dtype}")

Tipo de arr_int: int64
Tipo de arr_float: float64


In [50]:
arr_int32 = np.array([1, 2, 3], dtype=np.int32)
arr_float64 = np.array([1.0, 2.0], dtype=np.float64)

print(f"int32: {arr_int32.itemsize} bytes")
print(f"float64: {arr_float64.itemsize} bytes")

int32: 4 bytes
float64: 8 bytes


In [51]:
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
print(f"Tamaño: {arr.size} elementos")
print(f"Item size: {arr.itemsize} bytes")
print(f"Total bytes: {arr.nbytes} bytes")

Tamaño: 6 elementos
Item size: 4 bytes
Total bytes: 24 bytes


In [57]:
import numpy as np

# Crear diferentes tipos de arreglos
print("=" * 60)
print("EJEMPLO INTEGRADOR: CREACIÓN Y EXPLORACIÓN DE ARREGLOS")
print("=" * 60)

# 1. Arreglo 1-D desde lista
arr1d = np.array([10, 20, 30, 40, 50])
print("\n1. ARREGLO 1-D:")
print(arr1d)
print(f" Tipo: {type(arr1d)}")
print(f" Shape: {arr1d.shape}")
print(f" Ndim: {arr1d.ndim}")
print(f" Size: {arr1d.size}")
print(f" Dtype: {arr1d.dtype}")

# 2. Matriz 2-D
matriz = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])
print("\n2. MATRIZ 2-D:")
print(matriz)
print(f" Shape: {matriz.shape} (3 filas, 4 columnas)")
print(f" Ndim: {matriz.ndim}")
print(f" Size: {matriz.size}")


# 3. Arreglos con funciones especializadas
print("\n3. ARREGLOS CON FUNCIONES ESPECIALIZADAS:")
zeros = np.zeros((2, 3))
print(" Zeros (2x3):")
print(zeros)

ones = np.ones((2, 2), dtype=np.int32)
print("\n Ones (2x2, int32):")
print(ones)

rango = np.arange(0, 20, 3)
print("\n Arange (0 a 20, paso 3):")
print(rango)

EJEMPLO INTEGRADOR: CREACIÓN Y EXPLORACIÓN DE ARREGLOS

1. ARREGLO 1-D:
[10 20 30 40 50]
 Tipo: <class 'numpy.ndarray'>
 Shape: (5,)
 Ndim: 1
 Size: 5
 Dtype: int64

2. MATRIZ 2-D:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
 Shape: (3, 4) (3 filas, 4 columnas)
 Ndim: 2
 Size: 12

3. ARREGLOS CON FUNCIONES ESPECIALIZADAS:
 Zeros (2x3):
[[0. 0. 0.]
 [0. 0. 0.]]

 Ones (2x2, int32):
[[1 1]
 [1 1]]

 Arange (0 a 20, paso 3):
[ 0  3  6  9 12 15 18]


In [61]:
lineal = np.linspace(0, 1, 6)
print("\n Linspace (0 a 1, 6 valores):")
print(lineal)


 Linspace (0 a 1, 6 valores):
[0.  0.2 0.4 0.6 0.8 1. ]


In [62]:
# 4. Comparación de memoria
arr_int32 = np.array([1, 2, 3, 4, 5], dtype=np.int32)
arr_int64 = np.array([1, 2, 3, 4, 5], dtype=np.int64)
print("\n4. COMPARACIÓN DE MEMORIA:")
print(f" int32: {arr_int32.itemsize} bytes/elemento, "
f"{arr_int32.nbytes} bytes total")
print(f" int64: {arr_int64.itemsize} bytes/elemento, "
f"{arr_int64.nbytes} bytes total")


4. COMPARACIÓN DE MEMORIA:
 int32: 4 bytes/elemento, 20 bytes total
 int64: 8 bytes/elemento, 40 bytes total
